# Copyright 2024 (c) José Ángel de Bustos Pérez 
#   Author: José Ángel de Bustos Pérez <jadebustos@gmail.com>
#
# This file is part of the IdM workshop.
#
# IdM workshop is free software: you can redistribute it and/or modify it under the terms of 
# the GNU General Public License v3 as published by the Free Software Foundation.
# IdM workshop is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License v3 for more details.

# You should have received a copy of the GNU General Public License v3 along with the IdM workshop. 
# If not, see https://www.gnu.org/licenses/gpl-3.0.en.html.

- name: install rpms for nfs server
  ansible.builtin.dnf:
    name: "{{ rpms_nfs_server }}"
    state: latest

- name: configure nfs server v4.2
  ansible.builtin.copy:
    src: nfs.conf
    dest: /etc/nfs.conf
    owner: root
    group: root
    mode: 0644
    setype: etc_t

- name: mask nfsv3 services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    masked: no
  loop: 
    - "rpc-statd.service"
    - "rpcbind.service" 
    - "rpcbind.socket"

# - name: create users directory for vms
#   ansible.builtin.file:
#     path: /etc/systemd/system/nfs-mountd.service.d/
#     state: directory
#     owner: root
#     group: root
#     mode: 0644
#     setype: systemd_unit_file_t

# - name: configure nfs server not to listen to v3
#   ansible.builtin.copy:
#     src: v4only.conf
#     dest: /etc/systemd/system/nfs-mountd.service.d/v4only.conf
#     owner: root
#     group: root
#     mode: 0644
#     setype: systemd_unit_file_t

- name: nfs daemon reload
  ansible.builtin.systemd:
    name: nfs-mountd
    state: restarted
    daemon_reload: true

- name: configure nfs exports
  ansible.builtin.copy:
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
    setype: exports_t

- name: start nfs server
  ansible.builtin.systemd:
    name: nfs-server
    state: started
    enabled: true
    masked: no

#firewall-cmd --permanent --zone=libvirt --add-service={nfs,rpc-bind,mountd}
#firewall-cmd --permanent --zone=libvirt --add-port={5555/tcp,5555/udp,6666/tcp,6666/udp}
#firewall-cmd --reload

